<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_ExampleCow" Id="{d8a4f85f-5611-4e0a-b457-d3ba5721fd09}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ExampleCow
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>