<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{5c316f37-c00a-4846-b3a7-5df370ce17b6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR


fbReadCoe : FB_Read70x1CoeData;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbReadCoe(userNetId:= '172.21.148.67.2.1');]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>